/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: KontentAir
 * Environment: Production
 * Project Id: 63a40004-9ed0-01ea-00b5-4874cdeae75c
 */
export const collections = {} as const;
