/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: KontentAir
 * Environment: Production
 * Project Id: 63a40004-9ed0-01ea-00b5-4874cdeae75c
 */
export const contentTypes = {
  /**
   * [Component] Hero
   */
  component_hero: {
    codename: 'component_hero',
    id: 'aeb54257-a5a2-4fb5-aaf0-8ee4fc933cb4',
    externalId: undefined,
    name: '[Component] Hero',
    elements: {
      /**
       * Cards (modular_content)
       */
      cards: {
        codename: 'cards',
        id: '5aecdc8b-adb8-4007-b0c5-e79956e363ae',
        externalId: undefined,
        name: 'Cards',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Video (asset)
       */
      video: {
        codename: 'video',
        id: '6c1d6439-ea7f-4648-a57e-142d7227a844',
        externalId: undefined,
        name: 'Video',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * [Component] Listing
   */
  component_listing: {
    codename: 'component_listing',
    id: 'ff1ee335-422f-46f7-8b6c-39d8d5164337',
    externalId: undefined,
    name: '[Component] Listing',
    elements: {
      /**
       * Data (modular_content)
       */
      data: {
        codename: 'data',
        id: 'f294969b-f0be-42e9-bd01-3328dd3956ca',
        externalId: undefined,
        name: 'Data',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '53d47c08-30ee-45b0-aff6-14c6d38dee7b',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * [Component] Newsletter CTA
   */
  component_newsletter_cta: {
    codename: 'component_newsletter_cta',
    id: 'a72cbef8-b86b-4429-a98d-fb30c8b7106e',
    externalId: undefined,
    name: '[Component] Newsletter CTA',
    elements: {},
  },

  /**
   * [Component] Text Section
   */
  component_text_section: {
    codename: 'component_text_section',
    id: '55635040-1251-4fb5-a3b9-9082fb3a21f3',
    externalId: undefined,
    name: '[Component] Text Section',
    elements: {
      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: '2994d495-bb5b-4ddc-9d2b-af5d2840c7c2',
        externalId: undefined,
        name: 'Text',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'ebc85618-e407-4025-b249-ffa9aa189988',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Aircraft
   */
  aircraft: {
    codename: 'aircraft',
    id: '9afa79ad-95e8-4623-9644-829792aafe50',
    externalId: undefined,
    name: 'Aircraft',
    elements: {
      /**
       * ID (text)
       */
      id: {
        codename: 'id',
        id: '0fb86386-a055-4945-b95d-ba0d8b3affad',
        externalId: undefined,
        name: 'ID',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Type (multiple_choice)
       */
      type: {
        codename: 'type',
        id: 'f1c54d02-a498-4c7f-af40-ac89fc72f0d1',
        externalId: undefined,
        name: 'Type',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Airport
   */
  airport: {
    codename: 'airport',
    id: 'edc82ead-9eb7-4693-b67c-7a427acf7db7',
    externalId: undefined,
    name: 'Airport',
    elements: {
      /**
       * Code (text)
       */
      code: {
        codename: 'code',
        id: 'af7e91bb-4be3-42ca-9a70-011c2fef16b5',
        externalId: undefined,
        name: 'Code',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '6c276ae4-d3b5-45d6-b173-ff44d78d8a8e',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Destination
   */
  destination: {
    codename: 'destination',
    id: 'b23134f6-1711-412c-9849-076480cc89c8',
    externalId: undefined,
    name: 'Destination',
    elements: {
      /**
       * Photo (asset)
       */
      photo: {
        codename: 'photo',
        id: 'bbd9ab4c-aec1-48d8-95f4-141abd67e313',
        externalId: undefined,
        name: 'Photo',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: '6823ebe7-1e6d-4514-87ee-40f99fc4ae2e',
        externalId: undefined,
        name: 'Text',
        required: true,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '83294872-aa35-411d-a9af-179e91c5ef93',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Flight
   */
  flight: {
    codename: 'flight',
    id: '86ec5927-9972-4f46-94de-b96b781eb8bb',
    externalId: undefined,
    name: 'Flight',
    elements: {
      /**
       * Aircraft (modular_content)
       */
      aircraft: {
        codename: 'aircraft',
        id: 'c65900a9-bb6f-42a4-9100-7c5b71312299',
        externalId: undefined,
        name: 'Aircraft',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Arrival (date_time)
       */
      arrival: {
        codename: 'arrival',
        id: '989c3dd2-287f-4d3f-ad69-5dac457ac11e',
        externalId: undefined,
        name: 'Arrival',
        required: true,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Departure (date_time)
       */
      departure: {
        codename: 'departure',
        id: 'c99b36d1-a208-4018-96da-6fb86595e52d',
        externalId: undefined,
        name: 'Departure',
        required: true,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Destination (modular_content)
       */
      destination: {
        codename: 'destination',
        id: '4d72bc8e-10dc-4125-9540-1269fbb92505',
        externalId: undefined,
        name: 'Destination',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Origin (modular_content)
       */
      origin: {
        codename: 'origin',
        id: 'e1030abd-cec1-4775-9f45-d0e52b87e605',
        externalId: undefined,
        name: 'Origin',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Statuses (modular_content)
       */
      statuses: {
        codename: 'statuses',
        id: '143a0b14-1d13-46e7-9ec2-1ad2b4fb9644',
        externalId: undefined,
        name: 'Statuses',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Hero Card
   */
  hero_card: {
    codename: 'hero_card',
    id: '1b9bcc7d-5e4c-42e8-b1b3-b32caedd6e0d',
    externalId: undefined,
    name: 'Hero Card',
    elements: {
      /**
       * Text (rich_text)
       */
      text: {
        codename: 'text',
        id: '80bf0151-902a-4c3a-b35c-a2664faec459',
        externalId: undefined,
        name: 'Text',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '44557980-402f-436b-b68d-47ed8fe8c94f',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Status
   */
  status: {
    codename: 'status',
    id: '32a656f5-70e1-4618-8b2d-e3bf6948c708',
    externalId: undefined,
    name: 'Status',
    elements: {
      /**
       * Message (text)
       */
      message: {
        codename: 'message',
        id: 'ac1b8b40-06ef-42d6-819a-dcbd5bf95c6a',
        externalId: undefined,
        name: 'Message',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Message (custom)
       */
      chat: {
        codename: 'chat',
        id: 'daa0cda7-7850-4f44-b291-d60acb262b6d',
        externalId: undefined,
        name: 'Message',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },

      /**
       * Severity (multiple_choice)
       */
      severity: {
        codename: 'severity',
        id: '2dd06617-c22a-45d9-8998-541f706cf196',
        externalId: undefined,
        name: 'Severity',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },
} as const;
