import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Aircraft
 * Id: 9afa79ad-95e8-4623-9644-829792aafe50
 * Codename: aircraft
 */
export type AircraftModel = IContentItem<{
  /**
   * ID (text)
   * Required: false
   * Id: 0fb86386-a055-4945-b95d-ba0d8b3affad
   * Codename: id
   */
  id: Elements.TextElement;

  /**
   * Type (multiple_choice)
   * Required: false
   * Id: f1c54d02-a498-4c7f-af40-ac89fc72f0d1
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;
}>;
