import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Airport
 * Id: edc82ead-9eb7-4693-b67c-7a427acf7db7
 * Codename: airport
 */
export type AirportModel = IContentItem<{
  /**
   * Code (text)
   * Required: false
   * Id: af7e91bb-4be3-42ca-9a70-011c2fef16b5
   * Codename: code
   */
  code: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 6c276ae4-d3b5-45d6-b173-ff44d78d8a8e
   * Codename: title
   */
  title: Elements.TextElement;
}>;
