import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Newsletter CTA
 * Id: a72cbef8-b86b-4429-a98d-fb30c8b7106e
 * Codename: component_newsletter_cta
 */
export type ComponentNewsletterCtaModel = IContentItem<{}>;
