import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Text Section
 * Id: 55635040-1251-4fb5-a3b9-9082fb3a21f3
 * Codename: component_text_section
 */
export type ComponentTextSectionModel = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: 2994d495-bb5b-4ddc-9d2b-af5d2840c7c2
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Title (text)
   * Required: false
   * Id: ebc85618-e407-4025-b249-ffa9aa189988
   * Codename: title
   */
  title: Elements.TextElement;
}>;
