import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type DestinationModel } from './DestinationModel';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * [Component] Listing
 * Id: ff1ee335-422f-46f7-8b6c-39d8d5164337
 * Codename: component_listing
 */
export type ComponentListingModel = IContentItem<{
  /**
   * Data (modular_content)
   * Required: true
   * Id: f294969b-f0be-42e9-bd01-3328dd3956ca
   * Codename: data
   */
  data: Elements.LinkedItemsElement<DestinationModel>;

  /**
   * Title (text)
   * Required: true
   * Id: 53d47c08-30ee-45b0-aff6-14c6d38dee7b
   * Codename: title
   */
  title: Elements.TextElement;
}>;
