import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type AircraftModel } from './AircraftModel';
import { type AirportModel } from './AirportModel';
import { type StatusModel } from './StatusModel';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Flight
 * Id: 86ec5927-9972-4f46-94de-b96b781eb8bb
 * Codename: flight
 */
export type FlightModel = IContentItem<{
  /**
   * Aircraft (modular_content)
   * Required: true
   * Id: c65900a9-bb6f-42a4-9100-7c5b71312299
   * Codename: aircraft
   */
  aircraft: Elements.LinkedItemsElement<AircraftModel>;

  /**
   * Arrival (date_time)
   * Required: true
   * Id: 989c3dd2-287f-4d3f-ad69-5dac457ac11e
   * Codename: arrival
   */
  arrival: Elements.DateTimeElement;

  /**
   * Departure (date_time)
   * Required: true
   * Id: c99b36d1-a208-4018-96da-6fb86595e52d
   * Codename: departure
   */
  departure: Elements.DateTimeElement;

  /**
   * Destination (modular_content)
   * Required: true
   * Id: 4d72bc8e-10dc-4125-9540-1269fbb92505
   * Codename: destination
   */
  destination: Elements.LinkedItemsElement<AirportModel>;

  /**
   * Origin (modular_content)
   * Required: true
   * Id: e1030abd-cec1-4775-9f45-d0e52b87e605
   * Codename: origin
   */
  origin: Elements.LinkedItemsElement<AirportModel>;

  /**
   * Statuses (modular_content)
   * Required: false
   * Id: 143a0b14-1d13-46e7-9ec2-1ad2b4fb9644
   * Codename: statuses
   */
  statuses: Elements.LinkedItemsElement<StatusModel>;
}>;
