import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Hero Card
 * Id: 1b9bcc7d-5e4c-42e8-b1b3-b32caedd6e0d
 * Codename: hero_card
 */
export type HeroCardModel = IContentItem<{
  /**
   * Text (rich_text)
   * Required: false
   * Id: 80bf0151-902a-4c3a-b35c-a2664faec459
   * Codename: text
   */
  text: Elements.RichTextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 44557980-402f-436b-b68d-47ed8fe8c94f
   * Codename: title
   */
  title: Elements.TextElement;
}>;
