import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Status
 * Id: 32a656f5-70e1-4618-8b2d-e3bf6948c708
 * Codename: status
 */
export type StatusModel = IContentItem<{
  /**
   * Message (custom)
   * Required: false
   * Id: daa0cda7-7850-4f44-b291-d60acb262b6d
   * Codename: chat
   */
  chat: Elements.CustomElement;

  /**
   * Message (text)
   * Required: false
   * Id: ac1b8b40-06ef-42d6-819a-dcbd5bf95c6a
   * Codename: message
   */
  message: Elements.TextElement;

  /**
   * Severity (multiple_choice)
   * Required: false
   * Id: 2dd06617-c22a-45d9-8998-541f706cf196
   * Codename: severity
   */
  severity: Elements.MultipleChoiceElement;
}>;
